site_name: NewLang Programming Language

site_url: https://newlang.net/
site_description: A programming language with a simple no-keyword syntax for computing tensors and rational numbers with unlimited precision
site_author: rsashka
copyright: Copyright &copy; 2016-2023 Ryabikov Aleksandr

repo_name: rsashka/NewLang
repo_url: https://github.com/rsashka/newlang
#edit_uri: blob/dev/docs/

use_directory_urls: false
#docs_dir: output/site
site_dir: site

theme:
  name: material
  font: false
#  favicon: assets/logo.svg
#  analytics: {gtag: 'G-274394082'}
  palette:
    primary: blue
  highlightjs: true
  hljs_languages:
    - c
    - c++
    - bash


  features:
    - navigation.path
    - navigation.top
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
    - content.code.copy

  plugins:
    - offline
    - search
    - autolinks
    - i18n:
      docs_structure: folder
      languages:
        en: 
          name: English
          build: true
        ru: 
          name: Русский
          build: true


extra:
  alternate:
    - name: English
      link: /en/about.html
      lang: en
    - name: Русский
      link: /ru/about.html
      lang: ru

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rsashka
      name: Ryabikov Aleksandr on Github
