site_name: NewLang Programming Language

site_url: https://newlang.net/
site_description: A programming language with a simple no-keyword syntax for computing tensors and rational numbers with unlimited precision
site_author: rsashka
copyright: Copyright &copy; 2016-2023 Ryabikov Aleksandr

repo_name: rsashka/NewLang
repo_url: https://github.com/rsashka/newlang
edit_uri: blob/dev/docs/


theme:
  name: material
  font: false
  language: en
#  icon:
#    logo: material/file-document-multiple
#  favicon: assets/logo.svg
#  analytics: {gtag: 'G-274394082'}
  palette:
    primary: blue
  highlightjs: true
  hljs_languages:
    - c
    - c++
    - bash


  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.path
#    - toc.integrate 
    - navigation.expand
    - navigation.top
#    - navigation.sections
    - navigation.tabs
#    - navigation.tabs.sticky
    - content.code.annotate
    - content.code.copy

  plugins:
    - offline
    - search
    - autolinks
    - i18n:

      default_language: en
      default_language_only: false

      docs_structure: folder
#      material_alternate: true

      languages:
#        default:
#          name: Default (en)
#          build: true
#
        en: 
          name: English
          build: true
        ru: 
          name: Русский
          build: true

      nav_translations:
#         index.md
#         syntax.md
#         types.md
#            type_func.md
#            type_iter.md
#            type_native.md
            type_nor.md
            type_oop.md
            type_other.md
            type_str.md
         ops.md
         versions.md
         newlang_doc.md

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Русский
      link: /ru/
      lang: ru

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rsashka
      name: Ryabikov Aleksandr on Github
